
====================================
Iteration: 1
====================================
Traceback (most recent call last):
  File "C:\Users\manir\Desktop\intro to ML\Proj\JailbreakingLLMs\main.py", line 188, in <module>
    main(args)
  File "C:\Users\manir\Desktop\intro to ML\Proj\JailbreakingLLMs\main.py", line 38, in main
    extracted_attack_list = attackLM.get_attack(convs_list, processed_response_list)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manir\Desktop\intro to ML\Proj\JailbreakingLLMs\conversers.py", line 95, in get_attack
    outputs_list = self.model.batched_generate(full_prompts_subset,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manir\Desktop\intro to ML\Proj\JailbreakingLLMs\language_models.py", line 179, in batched_generate
    return [self.generate(conv, max_n_tokens, temperature, top_p) for conv in convs_list]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manir\Desktop\intro to ML\Proj\JailbreakingLLMs\language_models.py", line 158, in generate
    completion = self.model.completions.create(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manir\AppData\Roaming\Python\Python312\site-packages\anthropic\_utils\_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manir\AppData\Roaming\Python\Python312\site-packages\anthropic\resources\completions.py", line 386, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\manir\AppData\Roaming\Python\Python312\site-packages\anthropic\_base_client.py", line 1277, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manir\AppData\Roaming\Python\Python312\site-packages\anthropic\_base_client.py", line 954, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\manir\AppData\Roaming\Python\Python312\site-packages\anthropic\_base_client.py", line 980, in _request
    request = self._build_request(options, retries_taken=retries_taken)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manir\AppData\Roaming\Python\Python312\site-packages\anthropic\_base_client.py", line 465, in _build_request
    headers = self._build_headers(options, retries_taken=retries_taken)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manir\AppData\Roaming\Python\Python312\site-packages\anthropic\_base_client.py", line 413, in _build_headers
    self._validate_headers(headers_dict, custom_headers)
  File "C:\Users\manir\AppData\Roaming\Python\Python312\site-packages\anthropic\_client.py", line 189, in _validate_headers
    raise TypeError(
TypeError: "Could not resolve authentication method. Expected either api_key or auth_token to be set. Or for one of the `X-Api-Key` or `Authorization` headers to be explicitly omitted"
